"""Codex client adapter."""

from __future__ import annotations

import re
import shlex
from collections.abc import Callable
from pathlib import Path

from sync_ai_configs.helpers import (
    copy_file_if_different,
    deep_merge,
    ensure_dir,
    parse_duration_seconds,
    write_content_if_different,
)

from .base import Client


class CodexClient(Client):
    @property
    def name(self) -> str:
        return "codex"

    @property
    def config_dir(self) -> Path:
        return Path.home() / ".codex"

    def write_agent(self, slug: str, meta: dict, raw_content: str, prompt_src_path: Path) -> None:
        agent_dir = self.get_agents_dir() / slug
        ensure_dir(agent_dir)
        codex_prompt_path = agent_dir / "prompt.md"
        copy_file_if_different(prompt_src_path, codex_prompt_path)
        config_data = {
            "model": meta.get("models", {}).get("codex", "gpt-5"),
            "model_reasoning_effort": meta.get("reasoning_effort", "high"),
            "model_instructions_file": str(codex_prompt_path),
            "web_search": "live" if meta.get("web_search", True) else "off",
        }
        write_content_if_different(agent_dir / "config.toml", self._write_toml_config(config_data))

    def _build_mcp_entry(self, server_id: str, server: dict, secrets: dict) -> dict:
        secret_srv = self._get_secret_for_server(server_id, secrets)
        table: dict = {"enabled": server.get("enabled", True)}
        if server.get("method") in ("http", "sse"):
            table["url"] = server.get("url") or server.get("httpUrl", "")
            if server.get("bearer_token_env_var"):
                table["bearer_token_env_var"] = server["bearer_token_env_var"]
        else:
            table["command"] = server.get("command", "npx")
            table["args"] = server.get("args", [])
            env = self._build_mcp_env(server, secret_srv)
            if env:
                table["env"] = env
        if server.get("description"):
            table["description"] = str(server["description"])
        if "timeout" in server and server.get("timeout") is not None:
            try:
                sec = parse_duration_seconds(server["timeout"])
                table["startup_timeout_sec"] = sec
                table["tool_timeout_sec"] = sec
            except ValueError:
                print(f"  Warning: Invalid timeout for server '{server_id}': {server['timeout']!r}")
        return table

    def sync_mcp(self, servers: dict, secrets: dict, for_client: Callable[[dict, str], bool]) -> None:
        codex_mcp: dict = {}
        bearer_exports: list[str] = []
        for sid, srv in servers.items():
            if not for_client(srv, self.name):
                continue
            entry = self._build_mcp_entry(sid, srv, secrets)
            codex_mcp[sid] = entry
            var_name = srv.get("bearer_token_env_var")
            if var_name:
                val = (srv.get("env", {}).get(var_name) or "")
                if val:
                    bearer_exports.append(f"export {var_name}={shlex.quote(val)}")

        ensure_dir(self.config_dir)
        config_path = self.config_dir / "config.toml"
        existing = self._read_toml_config(config_path)
        existing["mcp_servers"] = self._merge_managed_servers(existing.get("mcp_servers", {}), codex_mcp)
        write_content_if_different(config_path, self._write_toml_config(existing))
        if any(e.get("env") for e in codex_mcp.values()):
            self._set_restrictive_permissions(config_path)
            self._warn_plaintext_secrets(config_path)

        if bearer_exports:
            mcp_env_path = self.config_dir / "mcp.env"
            content = "# Generated by sync_ai_configs. Source ~/.codex/mcp.env before running Codex.\n" + "\n".join(bearer_exports) + "\n"
            write_content_if_different(mcp_env_path, content)
            self._set_restrictive_permissions(mcp_env_path)
            self._warn_plaintext_secrets(mcp_env_path)

    def _build_client_config(self, settings: dict) -> dict:
        out: dict = {}
        if settings.get("suppress_unstable_features_warning", False):
            out["suppress_unstable_features_warning"] = True
        if settings.get("subagents", True):
            out.setdefault("features", {})
            out["features"]["multi_agent"] = True
            out["features"]["child_agents_md"] = True
        mode = settings.get("mode", "ask")
        if mode == "full-access":
            out["approval_policy"] = "never"
            out["sandbox_mode"] = "danger-full-access"
        elif mode == "ask-once":
            out["approval_policy"] = "untrusted"
            out["sandbox_mode"] = "workspace-write"
        else:
            out["approval_policy"] = "on-request"
            out["sandbox_mode"] = "workspace-write"
        return out

    def sync_client_config(self, settings: dict) -> None:
        updates = self._build_client_config(settings)
        if not updates:
            return
        ensure_dir(self.config_dir)
        config_path = self.config_dir / "config.toml"
        existing = self._read_toml_config(config_path)
        write_content_if_different(config_path, self._write_toml_config(deep_merge(existing, updates)))

    def sync_mcp_instructions(self, instructions: str) -> None:
        if not instructions or not instructions.strip():
            return
        ensure_dir(self.config_dir)
        config_path = self.config_dir / "config.toml"
        begin_marker = "<!-- BEGIN sync-ai-configs MCP instructions -->"
        end_marker = "<!-- END sync-ai-configs MCP instructions -->"
        block = f"{begin_marker}\n{instructions.strip()}\n{end_marker}"
        existing = self._read_toml_config(config_path)
        current = str(existing.get("developer_instructions", "") or "")
        pattern = re.compile(rf"{re.escape(begin_marker)}.*?{re.escape(end_marker)}", re.DOTALL)
        existing["developer_instructions"] = pattern.sub(block, current).strip() if pattern.search(current) else ((current.rstrip() + "\n\n" + block).strip() if current else block)
        write_content_if_different(config_path, self._write_toml_config(existing))
