"""Codex client adapter."""
from collections.abc import Callable
from pathlib import Path

import tomli
import tomli_w

from helpers import (
    copy_file_if_different,
    deep_merge,
    ensure_dir,
    write_content_if_different,
)

from .base import Client


class CodexClient(Client):
    @property
    def name(self) -> str:
        return "codex"

    @property
    def config_dir(self) -> Path:
        return Path.home() / ".codex"

    def write_agent(
        self,
        slug: str,
        meta: dict,
        raw_content: str,
        prompt_src_path: Path,
    ) -> None:
        agent_dir = self.get_agents_dir() / slug
        ensure_dir(agent_dir)
        codex_prompt_path = agent_dir / "prompt.md"
        copy_file_if_different(prompt_src_path, codex_prompt_path, backup=False)

        web_search_val = "live" if meta.get("web_search", True) else "off"
        codex_model = meta.get("models", {}).get("codex", "gpt-5")
        reasoning = meta.get("reasoning_effort", "high")
        config_content = f"""model = "{codex_model}"
model_reasoning_effort = "{reasoning}"
model_instructions_file = "{codex_prompt_path}"
web_search = "{web_search_val}"
"""
        write_content_if_different(
            agent_dir / "config.toml", config_content, backup=False
        )

    def _build_mcp_entry(self, server_id: str, server: dict, secrets: dict) -> dict:
        table: dict = {"enabled": server.get("enabled", True)}
        secret_srv = secrets.get("servers", {}).get(server_id, {})
        env_secrets = secret_srv.get("env", {})

        if server.get("method") in ("http", "sse"):
            table["url"] = server.get("url", "")
            if server.get("bearer_token_env_var"):
                table["bearer_token_env_var"] = server["bearer_token_env_var"]
        else:
            table["command"] = server.get("command", "npx")
            table["args"] = server.get("args", [])
            if env_secrets:
                table["env"] = {k: str(v) if v is not None else "" for k, v in env_secrets.items()}
        return table

    def sync_mcp(self, servers: dict, secrets: dict, for_client: Callable[[dict, str], bool]) -> None:
        codex_mcp: dict = {}
        bearer_exports: list[str] = []
        for sid, srv in servers.items():
            if not for_client(srv, self.name):
                continue
            codex_mcp[sid] = self._build_mcp_entry(sid, srv, secrets)
            var_name = srv.get("bearer_token_env_var")
            if var_name:
                val = (secrets.get("servers", {}).get(sid, {}).get("env", {}).get(var_name)) or ""
                if val:
                    bearer_exports.append(f'export {var_name}="{val}"')

        if not codex_mcp:
            return

        ensure_dir(self.config_dir)
        config_path = self.config_dir / "config.toml"
        try:
            existing: dict = {}
            if config_path.exists():
                with open(config_path, "rb") as f:
                    existing = tomli.load(f)
            if "mcp_servers" not in existing:
                existing["mcp_servers"] = {}
            existing["mcp_servers"] = deep_merge(
                dict(existing["mcp_servers"]),
                codex_mcp,
            )
            write_content_if_different(config_path, tomli_w.dumps(existing), backup=False)
        except (OSError, tomli.TOMLDecodeError) as e:
            print(f"  Warning: Could not update Codex config: {e}")

        if bearer_exports:
            mcp_env_path = self.config_dir / "mcp.env"
            content = (
                "# Generated by sync_ai_configs. Source ~/.codex/mcp.env before running Codex.\n"
                + "\n".join(bearer_exports)
                + "\n"
            )
            write_content_if_different(mcp_env_path, content, backup=False)

    def _build_client_config(self, settings: dict) -> dict:
        out: dict = {}
        subagents = settings.get("subagents", True)
        mode = settings.get("mode", "ask")

        if subagents:
            out.setdefault("features", {})
            out["features"]["multi_agent"] = True
            out["features"]["child_agents_md"] = True

        if mode == "full-access":
            out["approval_policy"] = "never"
            out["sandbox_mode"] = "danger-full-access"
        elif mode == "ask-once":
            out["approval_policy"] = "untrusted"
            out["sandbox_mode"] = "workspace-write"
        else:
            out["approval_policy"] = "on-request"
            out["sandbox_mode"] = "workspace-write"
        return out

    def sync_client_config(self, settings: dict) -> None:
        updates = self._build_client_config(settings)
        if not updates:
            return
        ensure_dir(self.config_dir)
        config_path = self.config_dir / "config.toml"
        try:
            existing: dict = {}
            if config_path.exists():
                with open(config_path, "rb") as f:
                    existing = tomli.load(f)
            merged = deep_merge(existing, updates)
            write_content_if_different(config_path, tomli_w.dumps(merged), backup=False)
        except (OSError, tomli.TOMLDecodeError) as e:
            print(f"  Warning: Could not update Codex client config: {e}")

    def clear_agents(self) -> None:
        import shutil
        agents_dir = self.get_agents_dir()
        if agents_dir.exists():
            shutil.rmtree(agents_dir)
            print(f"    Cleared agents: {agents_dir}")

    def clear_skills(self) -> None:
        import shutil
        skills_dir = self.get_skills_dir()
        if skills_dir.exists():
            shutil.rmtree(skills_dir)
            print(f"    Cleared skills: {skills_dir}")

    def clear_settings(self) -> None:
        config_path = self.config_dir / "config.toml"
        if config_path.exists():
            try:
                with open(config_path, "rb") as f:
                    existing = tomli.load(f)
                if "mcp_servers" in existing:
                    del existing["mcp_servers"]
                    write_content_if_different(config_path, tomli_w.dumps(existing), backup=False)
                    print(f"    Cleared MCP servers from {config_path}")
            except (OSError, tomli.TOMLDecodeError) as e:
                print(f"  Warning: Could not clear MCP from Codex config: {e}")

        mcp_env_path = self.config_dir / "mcp.env"
        if mcp_env_path.exists():
            mcp_env_path.unlink()
            print(f"    Deleted {mcp_env_path}")

    def get_oauth_src_path(self) -> Path | None:
        return self.config_dir / "auth.json"

    def get_oauth_stash_filename(self) -> str | None:
        return "codex-auth.json"
